[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
nyanc_core = { path = "../core" }
reporter = { path = "../reporter" }
ast ={ path = "../ast" }